// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/jfkonecn/gophitect/internal/features/common/components"
	"github.com/jfkonecn/gophitect/internal/features/common/layouts"
)

func DesignSystemPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = components.Navigation(components.PageDesignSystem).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, " <main><section><header><p>Developer Preview</p><h1>Design System</h1><p>A dev-only inventory of layout, color, typography, and interactive primitives currently available to the app.</p></header><section><div><p>Primary</p><p>Actions and active states</p></div><div><p>Secondary</p><p>Supporting emphasis</p></div><div><p>Accent</p><p>Highlights and decoration</p></div><div><p>Neutral</p><p>Dense surfaces</p></div></section><section><div><h2>Typography</h2><div><div><p>Display</p><p>Build clear interfaces.</p></div><div><p>Body</p><p>Use concise copy, strong hierarchy, and predictable spacing across pages.</p></div><code>font-mono / Fira Code</code></div></div><div><h2>Controls</h2><div><button>Primary</button> <button>Secondary</button> <button>Accent</button> <button>Outline</button></div><div><label><span>Name</span> <input type=\"text\"></label> <select><option>Default</option> <option>Compact</option></select></div></div></section><section><article><div><h2>Card Surface</h2><p>Cards group related content with a soft container and clear action area.</p><div><button>Action</button></div></div></article><div><h2>Info State</h2><p>Use state color sparingly for feedback that needs attention.</p></div><div><h2>Success State</h2><p>Reserve success for completed operations or healthy systems.</p></div></section></section></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Base("Design System").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
